{% set name = "ipyscales" %}
{% set version = "0.6.0" %}
{% set sha256 = "f2c42776482081b2771a2789623e1744a4e578f5d51644c1450b53738292b069" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - jupyter-packaging
    - nodejs
  run:
    - python
    - ipywidgets >=7,<8

test:
  imports:
    - {{ name }}

about:
  home: http://github.com/vidartf/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A widget library for scales

extra:
  recipe-maintainers:
    - vidartf
    - jasongrout
