travis:
  secure:
    BINSTAR_TOKEN: JUc2JO8sl9f0x03m3poO+EJEaBV9ztw8yuMbMYUNcpzyOXElWzwoA6KgUEVhW9GzitqGz8I5dfitThUb4fhT6t6Wn+GCBKM5Qc0hCuWKVQ3u3J+z69aKXlMMv8yOXExMAdWyS/hZ4XaUjG5xrYQimP4e7M8c4FcO1W/ODdHgc7h2wPZN5S5KxK1/HtdMmMv+0/Wxnw14yv0iU8tLIbDbfiAm74/oszWu3yXQFV3AEXxI8zTHdCiT2cyr6Ywl0m/JbJIrSfYKdUUJdY6fuC0fDOGVGbhrU+GokPTtGOtSoh+wFCmFhq9uiQzJ499nPo+QLJ0P/ftEcZTzNrcivN1pqV6wBzKtYFd/ykpmMojXKqRo9G9X1lOoXQlIDsCM20Sg0/VLn/V1HSNXIRvSYAhBWYT3s2gi4KeX6v7DknY/vNoM+txeXWwq+lO32/KBvTcH7RVzvTNMSdXTZzOwljgatA0b0bl9S8H/xEpm4x5D5tpMU8eJo3qoA/AcyIx8sU2jbQE8hDhcd3wTEehC9F68MSsjGV2PHMA4wQSq0tindW03qrm3wjG+no6etgKiPf0eW/ctBfT78zXzLr3+VqtfmtfZVU7Psi2X9wZtgtpT2UWLcyx5H6uqqhunrjGn95vDvEG0Ew8TJX63otkcJF85//AbnFTTnezuE/hdLkISi0I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
