travis:
  secure:
    BINSTAR_TOKEN: nmAZw8fUF4e2lKOHG1Jrk0vKdFZk2TdVkOElCFM7K8urlK9ole+nNCEjOzBZ2+pyY3Si9GHaReIUIYvBI/9/l1wcvMna+03UkVNsD9F3mEKumFlXtO/Xsn23E1Q9Vm7tW1BS+P5xiJfESch5es3tYr6nZaFtDwzcI+Dev0nTrsYFRjubpQmqexj+F84APAQqP7y2x8kdqLMSaNL2tsm2CCdjIadHbrnPTkEb1Cw4RGtWCRhgCaOfOc1V3hPuE5RW2Em0p2TaTcbj8/Z9oVcuazVkibssAHb5hfkd0L7fZdlbqXqrf9jERUaRSu1V9FMxlLT4VvWxlRKJG4clPez9JvTPT1giw3X+VTZK4svtGsAfbbr/2zN+P3pPeISLtKxq6YKCNzMfOJTu+roDf366D12mWRY2azpf4tpI/j7Pg2TZhEN4yOz+0afSpr18+XRmhz/JR9YNCdDCQJZfe/VBufn6ylJsL90ATXfjMrTjpicanBG1K7slg3stpntTG9UF9dK+zyEzHgLqWugsJ3Ig4mJVd6ST4GFtRd8syQBJS0S8XrJ0wvS3oZ+EYcL4n3fCTSMfARPeMbVjPq8FKht2r/cgVaE/I5xORO22PUmpfqNv4+suQNkWl079/L0u0hW4FKk7H4Hcxc/ZFOCJZeSqt21mV6U/e4HiDjrY88gQwbA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
